export {default as Login} from './Login';
// export {default as Profile} from './Profile';
// export {default as Home} from './Home';
// export {default as Search} from './Search';
// export {default as Details} from './Details';
export {default as Register} from './Register';
export {default as Splash} from './Splash';
// export {default as List} from './List';
export {default as ForgotPassword} from './ForgotPassword';
export {default as ResetPassword} from './ResetPassword';
export {default as VerifyCode} from './VerifyCode';
export {default as EditProfile} from './EditProfile';
// export {default as Settings} from './Settings';
